[package]
name = "rust-easyadmin-cli"
version = "0.1.0"
authors = ["Eden Reich <eden.reich@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"

[[bin]]
name = "easyadmin"
path = "main.rs"
